#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  7 20:03:28 2019

@author: Himanshu Kandpal
"""

# Define create_spreadsheet():
def create_spreadsheet(title,row_count=1000):
  print("Creating a spreadsheet called "+title)

# Call create_spreadsheet() below with the required arguments:
create_spreadsheet("Downloads")